# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'correction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Haeder_Frame = QtWidgets.QFrame(self.frame_2)
        self.Haeder_Frame.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Haeder_Frame.setFont(font)
        self.Haeder_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Haeder_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Haeder_Frame.setObjectName("Haeder_Frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Haeder_Frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Menu_Button = QtWidgets.QFrame(self.Haeder_Frame)
        self.Menu_Button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menu_Button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu_Button.setObjectName("Menu_Button")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Menu_Button)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2.addWidget(self.Menu_Button)
        self.Project_Name = QtWidgets.QFrame(self.Haeder_Frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Project_Name.setFont(font)
        self.Project_Name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Project_Name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Project_Name.setObjectName("Project_Name")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Project_Name)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.Project_Name)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.Project_Name, 0, QtCore.Qt.AlignHCenter)
        self.Action_Button = QtWidgets.QFrame(self.Haeder_Frame)
        self.Action_Button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Action_Button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Action_Button.setObjectName("Action_Button")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Action_Button)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.Action_Button)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/MinmumSize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.Action_Button)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/MaxmumSize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.Action_Button)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.Action_Button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.Haeder_Frame)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_17 = QtWidgets.QFrame(self.frame_12)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_17)
        self.label_6.setStyleSheet("     font:bold 12px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_6.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(self.frame_12)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit.setStyleSheet(" \n"
"                                        border-bottom: 2px solid rgb(65, 205, 82) ;\n"
"border-right: 2px solid rgb(65, 205, 82) ;\n"
"                                        border-radius: 3px;\n"
"                                        padding: 0 8px;\n"
"                                      \n"
"                                        font-size: 16px;\n"
"                                     ")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.horizontalLayout_6.addWidget(self.frame_16, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_7)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_19 = QtWidgets.QFrame(self.frame_13)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_19)
        self.label_7.setStyleSheet("     font:bold 12px;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_7.addWidget(self.frame_19, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_18 = QtWidgets.QFrame(self.frame_13)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_2.setStyleSheet(" \n"
"                                        border-bottom: 2px solid rgb(65, 205, 82) ;\n"
"border-right: 2px solid rgb(65, 205, 82) ;\n"
"                                        border-radius: 3px;\n"
"                                        padding: 0 8px;\n"
"                                      \n"
"                                        font-size: 16px;\n"
"                                     ")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_9.addWidget(self.lineEdit_2)
        self.horizontalLayout_7.addWidget(self.frame_18, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_6.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_7)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_23 = QtWidgets.QFrame(self.frame_14)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.frame_23)
        self.label_9.setStyleSheet("     font:bold 12px;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_9.addWidget(self.frame_23, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_20 = QtWidgets.QFrame(self.frame_14)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_4.setStyleSheet(" \n"
"                                        border-bottom: 2px solid rgb(65, 205, 82) ;\n"
"border-right: 2px solid rgb(65, 205, 82) ;\n"
"                                        border-radius: 3px;\n"
"                                        padding: 0 8px;\n"
"                                      \n"
"                                        font-size: 16px;\n"
"                                     ")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_13.addWidget(self.lineEdit_4)
        self.horizontalLayout_9.addWidget(self.frame_20, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.horizontalLayout_4.addWidget(self.frame_7, 0, QtCore.Qt.AlignTop)
        self.frame_24 = QtWidgets.QFrame(self.frame_5)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.line = QtWidgets.QFrame(self.frame_24)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_13.addWidget(self.line)
        self.horizontalLayout_4.addWidget(self.frame_24, 0, QtCore.Qt.AlignHCenter)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_26 = QtWidgets.QFrame(self.frame_8)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_28 = QtWidgets.QFrame(self.frame_26)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"        /*Border style*/\n"
"        border-style:solid;\n"
"        /*The width of the border is 4 pixels*/\n"
"        border-width:2px;\n"
"        /*Border fillet radius*/\n"
"        border-radius:10px;\n"
"        /*Border color*/\n"
"        border-color:rgb(65, 212, 124);\n"
"        /*typeface*/\n"
"        font:bold 14px;\n"
"        /*Font color*/\n"
"        color: rgba(0, 0, 0, 255);\n"
"        /*Lining*/\n"
"        padding:6px;\n"
"}\n"
"/*When the mouse hovers over a button*/\n"
"QPushButton:hover{\n"
"        background-color: rgba(100, 255, 100, 100);\n"
"        border-color: rgba(255, 255, 255,200);\n"
"        color:rgba(0,0,0,200);\n"
"}\n"
"/*When the button is pressed*/\n"
"QPushuButton:pressed{\n"
"        background-color: rgba(100, 255, 100, 200);\n"
"        border-color: rgba(255, 255, 255, 30);\n"
"        border-style:inset;\n"
"        color:rgba(0,0,0,100);\n"
"\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_16.addWidget(self.pushButton_5)
        self.horizontalLayout_10.addWidget(self.frame_28, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_27)
        self.lineEdit_5.setStyleSheet(" \n"
"                                        border-bottom: 2px solid rgb(65, 205, 82) ;\n"
"border-right: 2px solid rgb(65, 205, 82) ;\n"
"                                        border-radius: 3px;\n"
"                                        padding: 0 8px;\n"
"                                      \n"
"                                        font-size: 16px;\n"
"                                     ")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_20.addWidget(self.lineEdit_5)
        self.horizontalLayout_10.addWidget(self.frame_27, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_15.addWidget(self.frame_26)
        self.frame_25 = QtWidgets.QFrame(self.frame_8)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_30 = QtWidgets.QFrame(self.frame_25)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"        /*Border style*/\n"
"        border-style:solid;\n"
"        /*The width of the border is 4 pixels*/\n"
"        border-width:2px;\n"
"        /*Border fillet radius*/\n"
"        border-radius:10px;\n"
"        /*Border color*/\n"
"        border-color:rgb(65, 212, 124);\n"
"        /*typeface*/\n"
"        font:bold 14px;\n"
"        /*Font color*/\n"
"        color: rgba(0, 0, 0, 255);\n"
"        /*Lining*/\n"
"        padding:6px;\n"
"}\n"
"/*When the mouse hovers over a button*/\n"
"QPushButton:hover{\n"
"        background-color: rgba(100, 255, 100, 100);\n"
"        border-color: rgba(255, 255, 255,200);\n"
"        color:rgba(0,0,0,200);\n"
"}\n"
"/*When the button is pressed*/\n"
"QPushuButton:pressed{\n"
"        background-color: rgba(100, 255, 100, 200);\n"
"        border-color: rgba(255, 255, 255, 30);\n"
"        border-style:inset;\n"
"        color:rgba(0,0,0,100);\n"
"\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_17.addWidget(self.pushButton_6)
        self.horizontalLayout_11.addWidget(self.frame_30, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_29 = QtWidgets.QFrame(self.frame_25)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_29)
        self.lineEdit_6.setStyleSheet(" \n"
"                                        border-bottom: 2px solid rgb(65, 205, 82) ;\n"
"border-right: 2px solid rgb(65, 205, 82) ;\n"
"                                        border-radius: 3px;\n"
"                                        padding: 0 8px;\n"
"                                      \n"
"                                        font-size: 16px;\n"
"                                     ")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_21.addWidget(self.lineEdit_6)
        self.horizontalLayout_11.addWidget(self.frame_29, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_15.addWidget(self.frame_25)
        self.frame_15 = QtWidgets.QFrame(self.frame_8)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_32 = QtWidgets.QFrame(self.frame_15)
        self.frame_32.setStyleSheet("")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_32)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"        /*Border style*/\n"
"        border-style:solid;\n"
"        /*The width of the border is 4 pixels*/\n"
"        border-width:2px;\n"
"        /*Border fillet radius*/\n"
"        border-radius:10px;\n"
"        /*Border color*/\n"
"        border-color:rgb(65, 212, 124);\n"
"        /*typeface*/\n"
"        font:bold 14px;\n"
"        /*Font color*/\n"
"        color: rgba(0, 0, 0, 255);\n"
"        /*Lining*/\n"
"        padding:6px;\n"
"}\n"
"/*When the mouse hovers over a button*/\n"
"QPushButton:hover{\n"
"        background-color: rgba(100, 255, 100, 100);\n"
"        border-color: rgba(255, 255, 255,200);\n"
"        color:rgba(0,0,0,200);\n"
"}\n"
"/*When the button is pressed*/\n"
"QPushuButton:pressed{\n"
"        background-color: rgba(100, 255, 100, 200);\n"
"        border-color: rgba(255, 255, 255, 30);\n"
"        border-style:inset;\n"
"        color:rgba(0,0,0,100);\n"
"\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_18.addWidget(self.pushButton_7)
        self.horizontalLayout_12.addWidget(self.frame_32, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_31 = QtWidgets.QFrame(self.frame_15)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_31)
        self.lineEdit_7.setStyleSheet(" \n"
"                                        border-bottom: 2px solid rgb(65, 205, 82) ;\n"
"border-right: 2px solid rgb(65, 205, 82) ;\n"
"                                        border-radius: 3px;\n"
"                                        padding: 0 8px;\n"
"                                      \n"
"                                        font-size: 16px;\n"
"                                     ")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_22.addWidget(self.lineEdit_7)
        self.horizontalLayout_12.addWidget(self.frame_31, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_15.addWidget(self.frame_15)
        self.horizontalLayout_4.addWidget(self.frame_8, 0, QtCore.Qt.AlignTop)
        self.frame_33 = QtWidgets.QFrame(self.frame_5)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.line_2 = QtWidgets.QFrame(self.frame_33)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_14.addWidget(self.line_2)
        self.horizontalLayout_4.addWidget(self.frame_33, 0, QtCore.Qt.AlignHCenter)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_34 = QtWidgets.QFrame(self.frame_9)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_41 = QtWidgets.QFrame(self.frame_34)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.checkBox = QtWidgets.QCheckBox(self.frame_41)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_23.addWidget(self.checkBox)
        self.horizontalLayout_15.addWidget(self.frame_41, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_40 = QtWidgets.QFrame(self.frame_34)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_2 = QtWidgets.QLabel(self.frame_40)
        self.label_2.setStyleSheet("     font:bold 12px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_24.addWidget(self.label_2)
        self.horizontalLayout_15.addWidget(self.frame_40, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_19.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.frame_9)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_43 = QtWidgets.QFrame(self.frame_35)
        self.frame_43.setStyleSheet("     font:bold 12px;")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_43)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_3 = QtWidgets.QLabel(self.frame_43)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_25.addWidget(self.label_3)
        self.horizontalLayout_16.addWidget(self.frame_43, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_42 = QtWidgets.QFrame(self.frame_35)
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_42)
        self.lineEdit_8.setStyleSheet(" \n"
"                                        border-bottom: 2px solid rgb(65, 205, 82) ;\n"
"border-right: 2px solid rgb(65, 205, 82) ;\n"
"                                        border-radius: 3px;\n"
"                                        padding: 0 8px;\n"
"                                      \n"
"                                        font-size: 16px;\n"
"                                     ")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_27.addWidget(self.lineEdit_8)
        self.horizontalLayout_16.addWidget(self.frame_42, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_19.addWidget(self.frame_35)
        self.frame_39 = QtWidgets.QFrame(self.frame_9)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_39)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_45 = QtWidgets.QFrame(self.frame_39)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_45)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"        /*Border style*/\n"
"        border-style:solid;\n"
"        /*The width of the border is 4 pixels*/\n"
"        border-width:2px;\n"
"        /*Border fillet radius*/\n"
"        border-radius:10px;\n"
"        /*Border color*/\n"
"        border-color:rgb(65, 212, 124);\n"
"        /*typeface*/\n"
"        font:bold 14px;\n"
"        /*Font color*/\n"
"        color: rgba(0, 0, 0, 255);\n"
"        /*Lining*/\n"
"        padding:6px;\n"
"}\n"
"/*When the mouse hovers over a button*/\n"
"QPushButton:hover{\n"
"        background-color: rgba(100, 255, 100, 100);\n"
"        border-color: rgba(255, 255, 255,200);\n"
"        color:rgba(0,0,0,200);\n"
"}\n"
"/*When the button is pressed*/\n"
"QPushuButton:pressed{\n"
"        background-color: rgba(100, 255, 100, 200);\n"
"        border-color: rgba(255, 255, 255, 30);\n"
"        border-style:inset;\n"
"        color:rgba(0,0,0,100);\n"
"\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_28.addWidget(self.pushButton_4)
        self.horizontalLayout_17.addWidget(self.frame_45, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_44 = QtWidgets.QFrame(self.frame_39)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_44)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_44)
        self.lineEdit_9.setStyleSheet(" \n"
"                                        border-bottom: 2px solid rgb(65, 205, 82) ;\n"
"border-right: 2px solid rgb(65, 205, 82) ;\n"
"                                        border-radius: 3px;\n"
"                                        padding: 0 8px;\n"
"                                      \n"
"                                        font-size: 16px;\n"
"                                     ")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_30.addWidget(self.lineEdit_9)
        self.horizontalLayout_17.addWidget(self.frame_44, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_19.addWidget(self.frame_39)
        self.frame_36 = QtWidgets.QFrame(self.frame_9)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_46 = QtWidgets.QFrame(self.frame_36)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_46)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"        /*Border style*/\n"
"        border-style:solid;\n"
"        /*The width of the border is 4 pixels*/\n"
"        border-width:2px;\n"
"        /*Border fillet radius*/\n"
"        border-radius:10px;\n"
"        /*Border color*/\n"
"        border-color:rgb(65, 212, 124);\n"
"        /*typeface*/\n"
"        font:bold 14px;\n"
"        /*Font color*/\n"
"        color: rgba(0, 0, 0, 255);\n"
"        /*Lining*/\n"
"        padding:6px;\n"
"}\n"
"/*When the mouse hovers over a button*/\n"
"QPushButton:hover{\n"
"        background-color: rgba(100, 255, 100, 100);\n"
"        border-color: rgba(255, 255, 255,200);\n"
"        color:rgba(0,0,0,200);\n"
"}\n"
"/*When the button is pressed*/\n"
"QPushuButton:pressed{\n"
"        background-color: rgba(100, 255, 100, 200);\n"
"        border-color: rgba(255, 255, 255, 30);\n"
"        border-style:inset;\n"
"        color:rgba(0,0,0,100);\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_29.addWidget(self.pushButton_8)
        self.horizontalLayout_18.addWidget(self.frame_46, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_47 = QtWidgets.QFrame(self.frame_36)
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_47)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_47)
        self.lineEdit_10.setStyleSheet(" \n"
"                                        border-bottom: 2px solid rgb(65, 205, 82) ;\n"
"border-right: 2px solid rgb(65, 205, 82) ;\n"
"                                        border-radius: 3px;\n"
"                                        padding: 0 8px;\n"
"                                      \n"
"                                        font-size: 16px;\n"
"                                     ")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_31.addWidget(self.lineEdit_10)
        self.horizontalLayout_18.addWidget(self.frame_47, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_19.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.frame_9)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_38)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"        /*Border style*/\n"
"        border-style:solid;\n"
"        /*The width of the border is 4 pixels*/\n"
"        border-width:2px;\n"
"        /*Border fillet radius*/\n"
"        border-radius:10px;\n"
"        /*Border color*/\n"
"        border-color:rgb(65, 212, 124);\n"
"        /*typeface*/\n"
"        font:bold 14px;\n"
"        /*Font color*/\n"
"        color: rgba(0, 0, 0, 255);\n"
"        /*Lining*/\n"
"        padding:6px;\n"
"}\n"
"/*When the mouse hovers over a button*/\n"
"QPushButton:hover{\n"
"        background-color: rgba(100, 255, 100, 100);\n"
"        border-color: rgba(255, 255, 255,200);\n"
"        color:rgba(0,0,0,200);\n"
"}\n"
"/*When the button is pressed*/\n"
"QPushuButton:pressed{\n"
"        background-color: rgba(100, 255, 100, 200);\n"
"        border-color: rgba(255, 255, 255, 30);\n"
"        border-style:inset;\n"
"        color:rgba(0,0,0,100);\n"
"\n"
"}")
        self.pushButton_9.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/Plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_26.addWidget(self.pushButton_9)
        self.horizontalLayout_19.addWidget(self.frame_38)
        self.verticalLayout_19.addWidget(self.frame_37)
        self.horizontalLayout_4.addWidget(self.frame_9, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"        /*Border style*/\n"
"        border-style:solid;\n"
"        /*The width of the border is 4 pixels*/\n"
"        border-width:2px;\n"
"        /*Border fillet radius*/\n"
"        border-radius:10px;\n"
"        /*Border color*/\n"
"        border-color:rgb(65, 212, 124);\n"
"        /*typeface*/\n"
"        font:bold 14px;\n"
"        /*Font color*/\n"
"        color: rgba(0, 0, 0, 255);\n"
"        /*Lining*/\n"
"        padding:6px;\n"
"}\n"
"/*When the mouse hovers over a button*/\n"
"QPushButton:hover{\n"
"        background-color: rgba(100, 255, 100, 100);\n"
"        border-color: rgba(255, 255, 255,200);\n"
"        color:rgba(0,0,0,200);\n"
"}\n"
"/*When the button is pressed*/\n"
"QPushuButton:pressed{\n"
"        background-color: rgba(100, 255, 100, 200);\n"
"        border-color: rgba(255, 255, 255, 30);\n"
"        border-style:inset;\n"
"        color:rgba(0,0,0,100);\n"
"\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_20.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"        /*Border style*/\n"
"        border-style:solid;\n"
"        /*The width of the border is 4 pixels*/\n"
"        border-width:2px;\n"
"        /*Border fillet radius*/\n"
"        border-radius:10px;\n"
"        /*Border color*/\n"
"        border-color:rgb(65, 212, 124);\n"
"        /*typeface*/\n"
"        font:bold 14px;\n"
"        /*Font color*/\n"
"        color: rgba(0, 0, 0, 255);\n"
"        /*Lining*/\n"
"        padding:6px;\n"
"}\n"
"/*When the mouse hovers over a button*/\n"
"QPushButton:hover{\n"
"        background-color: rgba(100, 255, 100, 100);\n"
"        border-color: rgba(255, 255, 255,200);\n"
"        color:rgba(0,0,0,200);\n"
"}\n"
"/*When the button is pressed*/\n"
"QPushuButton:pressed{\n"
"        background-color: rgba(100, 255, 100, 200);\n"
"        border-color: rgba(255, 255, 255, 30);\n"
"        border-style:inset;\n"
"        color:rgba(0,0,0,100);\n"
"\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_20.addWidget(self.pushButton_12)
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-color:rgb(65, 212, 124);\n"
"        /*Border style*/\n"
"        border-style:solid;\n"
"        /*The width of the border is 4 pixels*/\n"
"        border-width:2px;\n"
"        /*Border fillet radius*/\n"
"        border-radius:10px;\n"
"        /*Border color*/\n"
"        border-color:rgb(65, 212, 124);\n"
"        /*typeface*/\n"
"        font:bold 14px;\n"
"        /*Font color*/\n"
"        color: rgba(0, 0, 0, 255);\n"
"        /*Lining*/\n"
"        padding:6px;\n"
"}\n"
"/*When the mouse hovers over a button*/\n"
"QPushButton:hover{\n"
"        background-color: rgba(100, 255, 100, 100);\n"
"        border-color: rgba(255, 255, 255,200);\n"
"        color:rgba(0,0,0,200);\n"
"}\n"
"/*When the button is pressed*/\n"
"QPushuButton:pressed{\n"
"        background-color: rgba(100, 255, 100, 200);\n"
"        border-color: rgba(255, 255, 255, 30);\n"
"        border-style:inset;\n"
"        color:rgba(0,0,0,100);\n"
"\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_21.addWidget(self.pushButton_10)
        self.horizontalLayout_5.addWidget(self.frame_11, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_51 = QtWidgets.QFrame(self.frame_4)
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_51)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.line_3 = QtWidgets.QFrame(self.frame_51)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_33.addWidget(self.line_3)
        self.verticalLayout_32.addWidget(self.frame_51)
        self.Footer_Frame = QtWidgets.QFrame(self.frame_4)
        self.Footer_Frame.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Footer_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Footer_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Footer_Frame.setObjectName("Footer_Frame")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.Footer_Frame)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_48 = QtWidgets.QFrame(self.Footer_Frame)
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_48)
        self.horizontalLayout_29.setContentsMargins(2, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_14 = QtWidgets.QLabel(self.frame_48)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_29.addWidget(self.label_14)
        self.horizontalLayout_22.addWidget(self.frame_48, 0, QtCore.Qt.AlignLeft)
        self.frame_49 = QtWidgets.QFrame(self.Footer_Frame)
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_49)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_15 = QtWidgets.QLabel(self.frame_49)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/newPrefix/Icons/Layers.png"))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_30.addWidget(self.label_15)
        self.horizontalLayout_22.addWidget(self.frame_49, 0, QtCore.Qt.AlignHCenter)
        self.frame_50 = QtWidgets.QFrame(self.Footer_Frame)
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_50)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_16 = QtWidgets.QLabel(self.frame_50)
        self.label_16.setMinimumSize(QtCore.QSize(0, 0))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_31.addWidget(self.label_16, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_22.addWidget(self.frame_50, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_32.addWidget(self.Footer_Frame)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Automated Question Correction"))
        self.label_6.setText(_translate("MainWindow", "Subject Name : "))
        self.label_7.setText(_translate("MainWindow", "Doctor\'s Name :"))
        self.label_9.setText(_translate("MainWindow", "Number Of Students : "))
        self.pushButton_5.setText(_translate("MainWindow", "Add a Ladder"))
        self.pushButton_6.setText(_translate("MainWindow", "Add Students"))
        self.pushButton_7.setText(_translate("MainWindow", "Add Papers"))
        self.label_2.setText(_translate("MainWindow", "Are There Models ?"))
        self.label_3.setText(_translate("MainWindow", "Model Name :"))
        self.pushButton_4.setText(_translate("MainWindow", "Add a Ladder"))
        self.pushButton_8.setText(_translate("MainWindow", "Add Papers"))
        self.pushButton_11.setText(_translate("MainWindow", "Exit"))
        self.pushButton_12.setText(_translate("MainWindow", "Back"))
        self.pushButton_10.setText(_translate("MainWindow", "Correction"))
        self.label_14.setText(_translate("MainWindow", "<Strong>Version : </Strong> 2.4.6"))
        self.label_16.setText(_translate("MainWindow", "<Strong>Created :</Strong> Copmany Name "))
# import Icon1_rc
