# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_ladder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_insert_ladder(object):
    def setupUi(self, insert_ladder):
        insert_ladder.setObjectName("insert_ladder")
        insert_ladder.resize(325, 792)
        insert_ladder.setMinimumSize(QtCore.QSize(325, 0))
        insert_ladder.setMaximumSize(QtCore.QSize(325, 16777215))
        self.centralwidget = QtWidgets.QWidget(insert_ladder)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label.setStyleSheet("background-color:rgba(62, 2, 104, 1);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.marks = QtWidgets.QTableWidget(self.centralwidget)
        self.marks.setInputMethodHints(QtCore.Qt.ImhPreferLatin)
        self.marks.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.marks.setGridStyle(QtCore.Qt.CustomDashLine)
        self.marks.setObjectName("marks")
        self.marks.setColumnCount(2)
        self.marks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.marks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(62, 2, 104, 10))
        self.marks.setHorizontalHeaderItem(1, item)
        self.marks.horizontalHeader().setCascadingSectionResizes(False)
        self.marks.horizontalHeader().setDefaultSectionSize(120)
        self.marks.horizontalHeader().setSortIndicatorShown(False)
        self.marks.horizontalHeader().setStretchLastSection(False)
        self.marks.verticalHeader().setCascadingSectionResizes(False)
        self.marks.verticalHeader().setSortIndicatorShown(False)
        self.marks.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.marks, 1, 0, 1, 2)
        self.ladder_ok = QtWidgets.QPushButton(self.centralwidget)
        self.ladder_ok.setStyleSheet("background-color:rgba(200, 200, 200, 40);\n"
"color:rgb(255,255,255);\n"
"background-color:rgba(108, 0, 255, 1);\n"
"background-color:rgba(62, 2, 104, 1);\n"
"")
        self.ladder_ok.setObjectName("ladder_ok")
        self.gridLayout.addWidget(self.ladder_ok, 2, 0, 1, 1)
        self.ladder_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.ladder_cancel.setStyleSheet("background-color:rgba(200, 200, 200, 40);\n"
"color:rgb(255,255,255);\n"
"background-color:rgba(108, 0, 255, 1);\n"
"background-color:rgba(62, 2, 104, 1);\n"
"")
        self.ladder_cancel.setObjectName("ladder_cancel")
        self.gridLayout.addWidget(self.ladder_cancel, 2, 1, 1, 1)
        insert_ladder.setCentralWidget(self.centralwidget)

        self.retranslateUi(insert_ladder)
        QtCore.QMetaObject.connectSlotsByName(insert_ladder)

    def retranslateUi(self, insert_ladder):
        _translate = QtCore.QCoreApplication.translate
        insert_ladder.setWindowTitle(_translate("insert_ladder", "Insert Ladder"))
        self.label.setText(_translate("insert_ladder", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Insert Ladder</span></p></body></html>"))
        self.marks.setSortingEnabled(False)
        item = self.marks.horizontalHeaderItem(0)
        item.setText(_translate("insert_ladder", "Answer"))
        item = self.marks.horizontalHeaderItem(1)
        item.setText(_translate("insert_ladder", "Mark"))
        self.ladder_ok.setText(_translate("insert_ladder", "Ok"))
        self.ladder_cancel.setText(_translate("insert_ladder", "Cancel"))
