# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ladder_mark.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ladder_m(object):
    def setupUi(self, ladder_m):
        ladder_m.setObjectName("ladder_m")
        ladder_m.resize(300, 792)
        ladder_m.setMinimumSize(QtCore.QSize(300, 0))
        ladder_m.setMaximumSize(QtCore.QSize(300, 16777215))
        self.centralwidget = QtWidgets.QWidget(ladder_m)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label.setStyleSheet("background-color:rgba(62, 2, 104, 1);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.ladder_ok = QtWidgets.QPushButton(self.centralwidget)
        self.ladder_ok.setStyleSheet("background-color:rgba(200, 200, 200, 40);\n"
"color:rgb(255,255,255);\n"
"background-color:rgba(108, 0, 255, 1);\n"
"background-color:rgba(62, 2, 104, 1);\n"
"")
        self.ladder_ok.setObjectName("ladder_ok")
        self.gridLayout.addWidget(self.ladder_ok, 0, 0, 1, 1)
        self.ladder_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.ladder_cancel.setStyleSheet("background-color:rgba(200, 200, 200, 40);\n"
"color:rgb(255,255,255);\n"
"background-color:rgba(108, 0, 255, 1);\n"
"background-color:rgba(62, 2, 104, 1);\n"
"")
        self.ladder_cancel.setObjectName("ladder_cancel")
        self.gridLayout.addWidget(self.ladder_cancel, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.marks = QtWidgets.QTableWidget(self.centralwidget)
        self.marks.setInputMethodHints(QtCore.Qt.ImhPreferLatin)
        self.marks.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.marks.setGridStyle(QtCore.Qt.CustomDashLine)
        self.marks.setObjectName("marks")
        self.marks.setColumnCount(1)
        self.marks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(62, 2, 104, 10))
        self.marks.setHorizontalHeaderItem(0, item)
        self.marks.horizontalHeader().setCascadingSectionResizes(False)
        self.marks.horizontalHeader().setDefaultSectionSize(240)
        self.marks.horizontalHeader().setSortIndicatorShown(False)
        self.marks.horizontalHeader().setStretchLastSection(False)
        self.marks.verticalHeader().setCascadingSectionResizes(False)
        self.marks.verticalHeader().setSortIndicatorShown(False)
        self.marks.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.marks, 1, 0, 1, 1)
        ladder_m.setCentralWidget(self.centralwidget)

        self.retranslateUi(ladder_m)
        QtCore.QMetaObject.connectSlotsByName(ladder_m)

    def retranslateUi(self, ladder_m):
        _translate = QtCore.QCoreApplication.translate
        ladder_m.setWindowTitle(_translate("ladder_m", "Marks"))
        self.label.setText(_translate("ladder_m", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Ladder Marks</span></p></body></html>"))
        self.ladder_ok.setText(_translate("ladder_m", "Ok"))
        self.ladder_cancel.setText(_translate("ladder_m", "Cancel"))
        self.marks.setSortingEnabled(False)
        item = self.marks.horizontalHeaderItem(0)
        item.setText(_translate("ladder_m", "Mark"))
