# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ladder_paper.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_insert_lader(object):
    def setupUi(self, insert_lader):
        insert_lader.setObjectName("insert_lader")
        insert_lader.resize(848, 860)
        insert_lader.setMinimumSize(QtCore.QSize(848, 860))
        insert_lader.setMaximumSize(QtCore.QSize(848, 860))
        insert_lader.setStyleSheet("background-color: rgba(255, 255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(insert_lader)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setStyleSheet("background-color:rgba(200, 200, 200, 40);\n"
"background-color:rgba(62, 2, 104, 1);\n"
"color:rgb(255,255,255);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        self.ladder_img = QtWidgets.QLabel(self.centralwidget)
        self.ladder_img.setMinimumSize(QtCore.QSize(621, 721))
        self.ladder_img.setMaximumSize(QtCore.QSize(621, 721))
        self.ladder_img.setText("")
        self.ladder_img.setObjectName("ladder_img")
        self.gridLayout.addWidget(self.ladder_img, 1, 0, 1, 3)
        self.save_ladder_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_ladder_btn.setMinimumSize(QtCore.QSize(170, 41))
        self.save_ladder_btn.setMaximumSize(QtCore.QSize(180, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save_ladder_btn.setFont(font)
        self.save_ladder_btn.setStyleSheet("background-color:rgba(200, 200, 200, 40);\n"
"color:rgb(255,255,255);\n"
"background-color:rgba(108, 0, 255, 1);\n"
"background-color:rgba(62, 2, 104, 1);\n"
"")
        self.save_ladder_btn.setObjectName("save_ladder_btn")
        self.gridLayout.addWidget(self.save_ladder_btn, 2, 0, 1, 1)
        self.answers = QtWidgets.QTableWidget(self.centralwidget)
        self.answers.setObjectName("answers")
        self.answers.setColumnCount(1)
        self.answers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.answers.setHorizontalHeaderItem(0, item)
        self.gridLayout.addWidget(self.answers, 1, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setMaximumSize(QtCore.QSize(10, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 3, 1, 1)
        self.cancel_ladder_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_ladder_btn.setMinimumSize(QtCore.QSize(170, 41))
        self.cancel_ladder_btn.setMaximumSize(QtCore.QSize(180, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancel_ladder_btn.setFont(font)
        self.cancel_ladder_btn.setStyleSheet("background-color:rgba(200, 200, 200, 40);\n"
"color:rgb(255,255,255);\n"
"background-color:rgba(108, 0, 255, 1);\n"
"background-color:rgba(62, 2, 104, 1);\n"
"")
        self.cancel_ladder_btn.setObjectName("cancel_ladder_btn")
        self.gridLayout.addWidget(self.cancel_ladder_btn, 2, 1, 1, 1)
        insert_lader.setCentralWidget(self.centralwidget)

        self.retranslateUi(insert_lader)
        QtCore.QMetaObject.connectSlotsByName(insert_lader)

    def retranslateUi(self, insert_lader):
        _translate = QtCore.QCoreApplication.translate
        insert_lader.setWindowTitle(_translate("insert_lader", "Lager Paper"))
        self.label.setText(_translate("insert_lader", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Correction Complete</span></p></body></html>"))
        self.save_ladder_btn.setText(_translate("insert_lader", "Save"))
        item = self.answers.horizontalHeaderItem(0)
        item.setText(_translate("insert_lader", "Answers"))
        self.cancel_ladder_btn.setText(_translate("insert_lader", "Cancel"))
