# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'print.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_print(object):
    def setupUi(self, print):
        print.setObjectName("print")
        print.resize(685, 853)
        self.centralwidget = QtWidgets.QWidget(print)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.project_name = QtWidgets.QLabel(self.centralwidget)
        self.project_name.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.project_name.setFont(font)
        self.project_name.setStyleSheet("background-color:rgba(200, 200, 200, 40);\n"
"background-color:rgba(62, 2, 104, 1);\n"
"color:rgb(255,255,255);\n"
"")
        self.project_name.setAlignment(QtCore.Qt.AlignCenter)
        self.project_name.setObjectName("project_name")
        self.gridLayout.addWidget(self.project_name, 0, 0, 1, 1)
        self.image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMinimumSize(QtCore.QSize(656, 728))
        self.image.setMaximumSize(QtCore.QSize(656, 728))
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 1, 0, 1, 1)
        self.ladder_ok = QtWidgets.QPushButton(self.centralwidget)
        self.ladder_ok.setStyleSheet("background-color:rgba(200, 200, 200, 40);\n"
"color:rgb(255,255,255);\n"
"background-color:rgba(108, 0, 255, 1);\n"
"background-color:rgba(62, 2, 104, 1);\n"
"")
        self.ladder_ok.setObjectName("ladder_ok")
        self.gridLayout.addWidget(self.ladder_ok, 2, 0, 1, 1)
        print.setCentralWidget(self.centralwidget)

        self.retranslateUi(print)
        QtCore.QMetaObject.connectSlotsByName(print)

    def retranslateUi(self, print):
        _translate = QtCore.QCoreApplication.translate
        print.setWindowTitle(_translate("print", "MainWindow"))
        self.project_name.setText(_translate("print", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Print Template</span></p></body></html>"))
        self.ladder_ok.setText(_translate("print", "print"))
